### ISSUE TITLE
findPlatforms returns empty OCF platform object

### ISSUE THREAD

**Issue by qiuzhong** [otcshare/iotivity-node#112] opened 2017-02-09 00:58 UTC
[iot-rest-api-server](https://github.com/01org/iot-rest-api-serve) use findPlatforms to discover OCF platforms. But it returns an empty object <strong>{}</strong>

# Steps:
1. Launch iot-rest-api-server:
	```
	# cd /usr/lib/node_modules/iot-rest-api-server
	# node index.js
	API server started on 2017-02-04T14:17:47.799Z [port: 8000, https: false]
	```

2. On the host side, send REST requests to the IoT device:

	When no OCF servers launched
	```
	$ curl http://<IoT IP>:8000/api/oic/d
	[]
	$ curl http://<IoT IP>:8000/api/oic/p
	[{}]
	```

	Launch the OCF servers on IoT device:

	```
	# /opt/iotivity/examples/resource/c/SimpleClientServer/ocserver -o 0 &
	```
	Then
	```
	$ curl http://<IoT IP>:8000/api/oic/d
	[{"di":"97970a2e-5113-4356-8da2-be798d3433fa","n":"myDeviceName","icv":"core.1.1.0"}]
	$ curl http://<IoT IP>:8000/api/oic/p
	[{"pi":"0A3E0D6F-DBF5-404E-8719-D6880042463A","mnmn":"myName","mnmo":"myModelNumber","mndt":"2016-01-15T00:00:00.000Z","mnpv":"myPlatformVersion","mnos":"myOS","mnfv":"myFirmwareVersion"},{}]
	```

	The last element of discovered OCF platforms is empty. According to the [REST API spec](https://github.com/01org/iot-rest-api-server/blob/master/doc/oic.wk.p.json#L59), it's invalid.

# Test environments
* [IoT-ref-kit image #101](http://iot-ref-kit.ostc.intel.com/download/builds/intel-iot-refkit_master/2017-02-06_04-34-54-build-101/images/intel-corei7-64/refkit-image-gateway-intel-corei7-64.wic.xz)
* iotivity-node 1.2.0-1 in this image.

**Comment by nagineni** [comment] 2017-02-23 11:01
Duplicate of https://github.com/otcshare/iotivity-node/issues/126

**Comment by qiuzhong** [comment] 2017-03-01 05:58
Close this issue and keep track of [issue#126](https://github.com/otcshare/iotivity-node/issues/126)

**Closed** 2017-03-01 05:58 UTC
