### ISSUE TITLE
iotivity-node on windows fails

### ISSUE THREAD

**Issue by as2902b** [otcshare/iotivity-node#96] opened 2016-11-30 11:08 UTC
Unable to find  module 'uuid' at runtime.,

**Comment by gabrielschulhof** [comment] 2016-11-30 20:53
That's weird. Is this on the maintenance branch?

**Comment by iamsanjeev** [comment] 2016-12-05 09:05
works fine.

**Comment by gabrielschulhof** [comment] 2016-12-06 00:09
@iamsanjeev OK, so can I close this issue?

**Comment by gabrielschulhof** [comment] 2016-12-09 13:13
I guess this is a duplicate of #95, what with the missing libuuid headers.

**Closed by gabrielschulhof** 2016-12-09 13:13 UTC
