### ISSUE TITLE
iotivity-node on Yocto

### ISSUE THREAD

**Issue by iamsanjeev** [otcshare/iotivity-node#99] opened 2016-12-09 23:58 UTC
Can you please explain the steps to run iotivity-node (specific version) on Yocto based platforms.
Do we need to build iotivity bindings natively on the platform.
This seems like an issue for most deployment units.

**Comment by poussa** [comment] 2016-12-12 09:31
@nagineni Can you take this one?

**Comment by rzr** [comment] 2016-12-12 09:38
I will share some notes at:
https://wiki.iotivity.org/yocto

Any plans to align meta-iot-web  to use 1.2.0 from meta-oic (upstreaming in progress) ?

Regards

**Comment by nagineni** [comment] 2016-12-12 10:11
@rzr I will update iotivity-node recipe to 1.2.0 as soon as we have iotivity 1.2.0 recipe in meta-oic master http://git.yoctoproject.org/cgit/cgit.cgi/meta-oic.

**Comment by rzr** [comment] 2016-12-12 10:20
hi @nagineni, thank you for feeback

I just sent iotivity_1.2.0 recipe (v2) to @kmaloor 
https://lists.iotivity.org/pipermail/iotivity-dev/2016-December/006373.html

But you can start working with this layer: 
https://github.com/tizenteam/meta-oic/tree/sandbox/pcoval/on/master/patch

Thanks again

**Comment by nagineni** [comment] 2016-12-12 10:21
@iamsanjeev 
We have recipes for both iotivity and iotivity-node in the following repos. 

meta-oic: http://git.yoctoproject.org/cgit/cgit.cgi/meta-oic/
meta-iot-web: https://github.com/ostroproject/meta-iot-web

You need to clone the repos first and then add the layers to your bitbake configuration in `conf/bblayers.conf`

Here are some instructions for building a custom Yocto image with iotivity and iotivity-node:
1. Pull the meta-oic and meta-iot-web layers.
2. Append layers to the list of layers in your `conf/bblayers.conf`
3. Include binary packages in the image by adding the following line in your `conf/local.conf`
`IMAGE_INSTALL_append += " iotivity iotivity-resource iotivity-node”`
4. Run `bitbake <image-name>` to build the image.

**Comment by rzr** [comment] 2016-12-12 10:23
yes @iamsanjeev wanted to build on device or crossbuild using yocto sdk, but I still believe it will be faster if using bitbake.

Beside updating iotivity-node.bb do you see any wall with 1.2.0 ? 

BTW don't hesitate to contact me for 1.2.1, it's on my plan too (maybe on jan 2017).

**Comment by nagineni** [comment] 2016-12-12 10:30
@rzr Good to hear that you already sent the updated recipe for review.

I already made a custom build with iotivity and iotivity-node v1.2.0 and they both seems to be working fine on Edison.

**Comment by rzr** [comment] 2016-12-12 10:33
ok cool, I am doing this on qemu at the moment, I will double check as well and document at:

https://wiki.iotivity.org/yocto

I will update doc,  once layers are validated, but it will be enough to move forward.

Thanks again for your check on edison.

**Comment by nagineni** [comment] 2016-12-12 10:39
@rzr Any reason why we are not building iotivity with `SECURED = 1`? I think we should enable this flag by default in the recipe.

**Comment by rzr** [comment] 2016-12-12 10:47
good question, I preferred to align to upstream's default parameters
but I have tested w/ SECURED=1 
it works too. (so I put it into comment, to be overloaded by .bbappend file)

Note that in upstream iotivity we're are about to switch secured to 1 for 1.3 or 2.0 upcoming branches...

**Comment by rzr** [comment] 2016-12-20 14:11
Hi I confirm I managed to make it run in unsecure mode,

but versions should be updated in high level mode, just like in:

https://github.com/TizenTeam/iotivity-node/blob/sandbox/pcoval/wip/js/switch-server-hilevel.js


I can make the change and check again, should PR be done in master branch?

More to come at:

https://wiki.iotivity.org/yocto

I can even share an image with everything in (based on GENIVI)

https://wiki.iotivity.org/automotive#work_in_progress_120

Regards

**Comment by rzr** [comment] 2016-12-20 22:41
iotivity 1.2.0 landed in meta-oic
http://git.yoctoproject.org/cgit/cgit.cgi/meta-oic/log/?h=1.2.0

Now to check, which branch of iotivity-node should I rebase on ?

Mine is:
https://github.com/TizenTeam/iotivity-node/commits/maintenance

Then I can try to build an image for pi3 as requested in:
https://github.com/otcshare/iotivity-node/issues/97

**Comment by iamsanjeev** [comment] 2016-12-21 06:16
@rzr, maintenance is what we are using for testing against 1.2.0. You need to check for security.
My request is let's make SECURE=0 as default for yocto. Let this be something user can enable. It simplifies development and later we can flip it ON.

**Comment by nagineni** [comment] 2016-12-21 07:30
@rzr Glad to hear that the patch landed in meta-oic. I will create a PR for updating iotivity-node recipe to 1.2.0 once the local build is okay. For testing purposes, you can use maintenance branch of iotivity-node, but there are still some issues which needs to be addressed before we merge that branch to master.

**Comment by nagineni** [comment] 2016-12-22 08:43
@rzr, the issues are related to periodic discovery of the resources/devices/platforms and also the missing delete event. Discovery works once, but we see multiple entries of the same resources if we do the discovery again. Maintenance branch is supposed to fix the issue, but it is still reproducible.

**Comment by gabrielschulhof** [comment] 2016-12-22 10:31
@nagineni Lemme get this straight about the duplicates you're getting. With each round of discovery, are you getting one resource per interface, resulting in multiple instances of the same resource, because the device has multiple interfaces?

If so, then IIRC we agreed that this is something the end-user's application must fix.

**Comment by nagineni** [comment] 2016-12-22 11:11
@gabrielschulhof Checking this on my host and it has only one interface. I am getting duplicates on rediscover even if the device has only one interface.

**Comment by gabrielschulhof** [comment] 2016-12-22 23:00
@nagineni gotcha. I'll re-do the test to make sure the number of copies stays the sane across discovery rounds.

**Comment by rzr** [comment] 2016-12-23 00:24
FYI I just sent a revision of meta-oic for ostroos and AGL , but it should not affect you,
if you're curious it's at:
https://github.com/TizenTeam/meta-oic/commits/sandbox/pcoval/on/master/review

**Comment by gabrielschulhof** [comment] 2016-12-23 15:26
@nagineni [Awesome catch!](https://github.com/gabrielschulhof/iotivity-node/commit/98a0831cc7314f81d07bcfc993a03622ee0fd06f#diff-075a851626815c29f95a3b3cc1649222R69) Thank you!

**Comment by mythi** [comment] 2017-01-10 08:14
On Fri, Dec 23, 2016 at 2:24 AM, rzr wrote:

> FYI I just sent a revision of meta-oic for ostroos and AGL , but it should
> not affect you,
> if you're curious it's at:
> https://github.com/TizenTeam/meta-oic/commits/sandbox/
> pcoval/on/master/review
>
>
Did you send these to meta-oic maintainer as well?

-- Mikko

**Comment by rzr** [comment] 2017-01-10 09:03
Yes I did send a few patches to @kmaloor, i will contact him again if no feedback

**Comment by rzr** [comment] 2017-01-24 18:02
@mythi is everything fine with 
https://github.com/ostroproject/meta-iot-web/pulls
?

**Comment by rzr** [comment] 2017-04-21 14:09
I think this bug can be closed, unless we want latest iotivity version 1.2.1 in meta-oit-web

As suggested at:
https://github.com/ostroproject/meta-iot-web/pull/25

**Comment by rzr** [comment] 2017-06-09 09:36
I checked 1.2.1 so it can land in master:
https://github.com/otcshare/iotivity-node/pull/136

**Closed** 2017-06-09 12:05 UTC
