### ISSUE TITLE
Missing 'delete' event in ClientResource implementation

### ISSUE THREAD

**Issue by nagineni** [otcshare/iotivity-node#92] opened 2016-11-28 13:36 UTC
`ClientResource` should support the `delete` event as specified in the spec.

Spec:
The `delete` event is fired on a `ClientResource` object when the implementation gets notified about the resource being deleted or unregistered from the OCF network.

**Comment by nagineni** [comment] 2016-11-28 13:36
@gabrielschulhof

**Comment by zolkis** [comment] 2016-11-28 15:03
The problem is that the OCF 1.1 spec doesn't say anything about presence any more (at least I didn't find it).

iotivity does still implement presence at the moment, but it is based on the "oic/ad" resource type, which again is not in the current spec any more ("oic.wk.ad" not defined).

Perhaps we should ask on the mailing list what's going on. Is it now a resource private to the network and you need to discover first if there is a resource of tyoe "oic/ad" that provides presence? But even then, where is the presence resource type and resource specified?

Also, on the iotivity-dev mailing list they still refer to "oic/ad" which seems odd. The two plausible explanation I have is either that 
- it's me who has not found where it's spec'd, 
- or it's been discontinued in favor of another mechanism.

@thiagomacieira could you help?

**Comment by thiagomacieira** [comment] 2016-11-29 01:46
I think presence is a misfeature and don't mind if it silently disappears.

But what does that have to do with delete?

**Comment by zolkis** [comment] 2016-11-29 08:49
The `delete` event is fired (was intended to be fired) when a client implementation gets a notification that implies the resource is gone (e.g. presence update from the device that owns the resource). 

Also, there is a `devicelost` event on the client API object. Client applications can choose which event to listen/react to.

If there is no way to know when a device, or resource go down in an OCF network, then clients need to do periodic discovery requests, which is not efficient.

A work flow of discovery + status/lifecycle updates would be more efficient.

Resource directory is even more efficient. If its existence is guaranteed in an OCF network, it could low-pass filter all the resource/device lifecycle events.

**Comment by thiagomacieira** [comment] 2016-11-29 17:34
I agree that it's not efficient, but it's what we have for now.

For OCF 1.1 spec, we should start thinking of how to make things more efficient. For example, one item on my mind is to make Resource Directories mandatory, which would help you. Not completely, because RDs are caches and the device may have disappeared anyway.

**Comment by gabrielschulhof** [comment] 2017-01-28 11:28
This is fixed in 1.2.0-1.

**Closed by gabrielschulhof** 2017-01-28 11:28 UTC
